<?php
/** Módulo: Cadastro de Jovem */
require_once __DIR__ . '/../config/app.php';
require_once __DIR__ . '/../includes/crud_helper.php';

renderCrud([
    'mod' => 'cadastro_jovem',
    'table' => 'cadastro_jovem',
    'pk' => 'id_jovem',
    'singular' => 'Jovem',
    'plural' => 'Jovens Aprendizes',
    'columns' => ['id_inscricao','matricula','inativo','nome_completo','nome_social','cpf','rg','orgao_emissor','data_emissao_rg','genero','orientacao_sexual','nascimento','naturalidade','nacionalidade','estado_civil','cor_raca','destro_canhoto','pcd','deficiencia_descricao','reservista','cnh','tipo_cnh','nis_pis','ctps_numero','ctps_serie','banco','agencia','conta','cep','endereco','numero','complemento','bairro','municipio','regiao','email','telefone','celular','recado','outros_fones','escolaridade','escola','periodo','serie','ra','fundacao','cras','antecedentes','ja_trabalhou','ctps_assinada','renda_familiar','aprovacao_status','cad_unico','observacoes_sociais','data_cadastro'],
    'searchable' => ['nome_completo','cpf','matricula','email','municipio'],
    'grid_columns' => [
        'id_jovem' => 'ID',
        'matricula' => 'Matrícula',
        'nome_completo' => 'Nome',
        'cpf' => 'CPF',
        'genero' => 'Gênero',
        'municipio' => 'Município',
        'inativo' => 'Inativo',
        'aprovacao_status' => 'Status',
    ],
    'grid_columns_keys' => ['nome_completo'],
    'badge_fields' => [
        'inativo' => ['N' => 'badge-success', 'S' => 'badge-danger'],
        'aprovacao_status' => ['Aprovado' => 'badge-success', 'Em Análise' => 'badge-warning', 'Reprovado' => 'badge-danger'],
    ],
    'fields' => [
        ['name'=>'nome_completo', 'label'=>'Nome Completo', 'required'=>true],
        ['name'=>'nome_social', 'label'=>'Nome Social'],
        ['name'=>'cpf', 'label'=>'CPF'],
        ['name'=>'rg', 'label'=>'RG'],
        ['name'=>'orgao_emissor', 'label'=>'Órgão Emissor'],
        ['name'=>'data_emissao_rg', 'label'=>'Data Emissão RG', 'type'=>'date'],
        ['name'=>'genero', 'label'=>'Gênero', 'type'=>'select', 'options'=>['Masculino'=>'Masculino','Feminino'=>'Feminino','Não-binário'=>'Não-binário','Outro'=>'Outro']],
        ['name'=>'nascimento', 'label'=>'Data Nascimento', 'type'=>'date'],
        ['name'=>'nacionalidade', 'label'=>'Nacionalidade', 'default'=>'Brasileira'],
        ['name'=>'naturalidade', 'label'=>'Naturalidade'],
        ['name'=>'estado_civil', 'label'=>'Estado Civil', 'type'=>'select', 'options'=>['Solteiro'=>'Solteiro','Casado'=>'Casado','Divorciado'=>'Divorciado','Viúvo'=>'Viúvo']],
        ['name'=>'cor_raca', 'label'=>'Cor/Raça', 'type'=>'select', 'options'=>['Branco'=>'Branco','Negro'=>'Negro','Pardo'=>'Pardo','Amarelo'=>'Amarelo','Indígena'=>'Indígena']],
        ['name'=>'email', 'label'=>'E-mail', 'type'=>'email'],
        ['name'=>'telefone', 'label'=>'Telefone'],
        ['name'=>'celular', 'label'=>'Celular'],
        ['name'=>'cep', 'label'=>'CEP'],
        ['name'=>'endereco', 'label'=>'Endereço'],
        ['name'=>'numero', 'label'=>'Número'],
        ['name'=>'complemento', 'label'=>'Complemento'],
        ['name'=>'bairro', 'label'=>'Bairro'],
        ['name'=>'municipio', 'label'=>'Município'],
        ['name'=>'escolaridade', 'label'=>'Escolaridade'],
        ['name'=>'escola', 'label'=>'Escola'],
        ['name'=>'periodo', 'label'=>'Período'],
        ['name'=>'serie', 'label'=>'Série'],
        ['name'=>'matricula', 'label'=>'Matrícula Interna'],
        ['name'=>'inativo', 'label'=>'Inativo', 'type'=>'select', 'options'=>['N'=>'Não','S'=>'Sim'], 'default'=>'N'],
        ['name'=>'aprovacao_status', 'label'=>'Status Aprovação', 'type'=>'select', 'options'=>['Em Análise'=>'Em Análise','Aprovado'=>'Aprovado','Reprovado'=>'Reprovado'], 'default'=>'Em Análise'],
        ['name'=>'data_cadastro', 'label'=>'Data Cadastro', 'type'=>'date'],
        ['name'=>'observacoes_sociais', 'label'=>'Observações Sociais', 'type'=>'textarea', 'span'=>'2'],
    ],
]);
